# Generated by Django 3.1.7 on 2021-03-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('tipo_refeicao', models.CharField(choices=[('breakfast', 'Café da manhã'), ('lunch', 'Almoço'), ('supper', 'Jantar'), ('snack', 'Lanche')], max_length=15, verbose_name='Tipo de Refeição')),
                ('nivel_dificuldade', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=15, verbose_name='Nível de dificuldade')),
                ('numero_pessoa', models.IntegerField(verbose_name='Numero de pessoas que serve')),
                ('estapas_preparacao', models.TextField(verbose_name='Etapas de preparo')),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do ingradiente')),
                ('medida', models.CharField(max_length=50, verbose_name='Medida do ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receita.receita')),
            ],
        ),
    ]
